# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frontpage.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(140, 40, 521, 441))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.logo = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.logo.setAlignment(QtCore.Qt.AlignCenter)
        self.logo.setObjectName("logo")
        self.verticalLayout.addWidget(self.logo)
        self.currentTime = QtWidgets.QDateTimeEdit(self.verticalLayoutWidget)
        self.currentTime.setAlignment(QtCore.Qt.AlignCenter)
        self.currentTime.setReadOnly(True)
        self.currentTime.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.currentTime.setDate(QtCore.QDate(2020, 6, 18))
        self.currentTime.setMinimumTime(QtCore.QTime(0, 0, 0))
        self.currentTime.setCurrentSection(QtWidgets.QDateTimeEdit.YearSection)
        self.currentTime.setObjectName("currentTime")
        self.verticalLayout.addWidget(self.currentTime)
        spacerItem = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.evalUserInputLine = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.evalUserInputLine.setObjectName("evalUserInputLine")
        self.verticalLayout.addWidget(self.evalUserInputLine)
        spacerItem1 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.whosInButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.whosInButton.setObjectName("whosInButton")
        self.verticalLayout.addWidget(self.whosInButton)
        spacerItem2 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem2)
        self.mediaButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.mediaButton.setObjectName("mediaButton")
        self.verticalLayout.addWidget(self.mediaButton)
        spacerItem3 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem3)
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.logo.setText(_translate("MainWindow", "Accutrack Cloneeeee"))
        self.currentTime.setToolTip(_translate("MainWindow", "Current time"))
        self.currentTime.setDisplayFormat(_translate("MainWindow", "M/d/yy h:mm:ss AP"))
        self.whosInButton.setToolTip(_translate("MainWindow", "Show who\'s currently signed in"))
        self.whosInButton.setText(_translate("MainWindow", "Who\'s In?"))
        self.mediaButton.setToolTip(_translate("MainWindow", "Check out media under student\'s name or see all media currently checked out"))
        self.mediaButton.setText(_translate("MainWindow", "Media Checkout"))
        self.pushButton.setToolTip(_translate("MainWindow", "Show events happening today"))
        self.pushButton.setText(_translate("MainWindow", "Events"))
