# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addCourseDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_addCourseDialog(object):
    def setupUi(self, addCourseDialog):
        addCourseDialog.setObjectName("addCourseDialog")
        addCourseDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        addCourseDialog.resize(691, 451)
        addCourseDialog.setMinimumSize(QtCore.QSize(691, 451))
        addCourseDialog.setModal(True)
        self.verticalLayoutWidget = QtWidgets.QWidget(addCourseDialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 671, 349))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.subjectLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.subjectLabel.setMinimumSize(QtCore.QSize(57, 41))
        self.subjectLabel.setObjectName("subjectLabel")
        self.verticalLayout.addWidget(self.subjectLabel, 0, QtCore.Qt.AlignHCenter)
        self.subjectInput = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.subjectInput.sizePolicy().hasHeightForWidth())
        self.subjectInput.setSizePolicy(sizePolicy)
        self.subjectInput.setMinimumSize(QtCore.QSize(300, 35))
        self.subjectInput.setObjectName("subjectInput")
        self.verticalLayout.addWidget(self.subjectInput, 0, QtCore.Qt.AlignHCenter)
        self.catalogLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.catalogLabel.setMinimumSize(QtCore.QSize(60, 42))
        self.catalogLabel.setObjectName("catalogLabel")
        self.verticalLayout.addWidget(self.catalogLabel, 0, QtCore.Qt.AlignHCenter)
        self.catalogInput = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.catalogInput.sizePolicy().hasHeightForWidth())
        self.catalogInput.setSizePolicy(sizePolicy)
        self.catalogInput.setMinimumSize(QtCore.QSize(300, 35))
        self.catalogInput.setObjectName("catalogInput")
        self.verticalLayout.addWidget(self.catalogInput, 0, QtCore.Qt.AlignHCenter)
        self.sectionLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.sectionLabel.setMinimumSize(QtCore.QSize(60, 41))
        self.sectionLabel.setObjectName("sectionLabel")
        self.verticalLayout.addWidget(self.sectionLabel, 0, QtCore.Qt.AlignHCenter)
        self.sectionInput = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sectionInput.sizePolicy().hasHeightForWidth())
        self.sectionInput.setSizePolicy(sizePolicy)
        self.sectionInput.setMinimumSize(QtCore.QSize(300, 35))
        self.sectionInput.setObjectName("sectionInput")
        self.verticalLayout.addWidget(self.sectionInput, 0, QtCore.Qt.AlignHCenter)
        self.professorLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.professorLabel.setObjectName("professorLabel")
        self.verticalLayout.addWidget(self.professorLabel, 0, QtCore.Qt.AlignHCenter)
        self.professorDropDown = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.professorDropDown.setMinimumSize(QtCore.QSize(300, 35))
        self.professorDropDown.setEditable(True)
        self.professorDropDown.setObjectName("professorDropDown")
        self.verticalLayout.addWidget(self.professorDropDown, 0, QtCore.Qt.AlignHCenter)
        self.cancelButton = QtWidgets.QPushButton(addCourseDialog)
        self.cancelButton.setGeometry(QtCore.QRect(220, 390, 99, 40))
        self.cancelButton.setMinimumSize(QtCore.QSize(99, 40))
        self.cancelButton.setObjectName("cancelButton")
        self.addButton = QtWidgets.QPushButton(addCourseDialog)
        self.addButton.setGeometry(QtCore.QRect(350, 390, 99, 40))
        self.addButton.setMinimumSize(QtCore.QSize(99, 40))
        self.addButton.setObjectName("addButton")

        self.retranslateUi(addCourseDialog)
        QtCore.QMetaObject.connectSlotsByName(addCourseDialog)

    def retranslateUi(self, addCourseDialog):
        _translate = QtCore.QCoreApplication.translate
        addCourseDialog.setWindowTitle(_translate("addCourseDialog", "Add Course"))
        self.subjectLabel.setText(_translate("addCourseDialog", "Subject (Course)*"))
        self.catalogLabel.setText(_translate("addCourseDialog", "Catalog (Course Number)"))
        self.sectionLabel.setText(_translate("addCourseDialog", "Section"))
        self.professorLabel.setText(_translate("addCourseDialog", "Professor"))
        self.cancelButton.setText(_translate("addCourseDialog", "Cancel"))
        self.addButton.setText(_translate("addCourseDialog", "Add"))
