# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'deleteStudentDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DeleteStudentDialog(object):
    def setupUi(self, DeleteStudentDialog):
        DeleteStudentDialog.setObjectName("DeleteStudentDialog")
        DeleteStudentDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        DeleteStudentDialog.resize(480, 199)
        self.message = QtWidgets.QLabel(DeleteStudentDialog)
        self.message.setGeometry(QtCore.QRect(20, 30, 321, 35))
        self.message.setMinimumSize(QtCore.QSize(120, 35))
        self.message.setObjectName("message")
        self.nameLabel = QtWidgets.QLabel(DeleteStudentDialog)
        self.nameLabel.setGeometry(QtCore.QRect(20, 80, 441, 35))
        self.nameLabel.setMinimumSize(QtCore.QSize(250, 35))
        self.nameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.nameLabel.setObjectName("nameLabel")
        self.cancelButton = QtWidgets.QPushButton(DeleteStudentDialog)
        self.cancelButton.setGeometry(QtCore.QRect(70, 140, 131, 35))
        self.cancelButton.setMinimumSize(QtCore.QSize(131, 35))
        self.cancelButton.setObjectName("cancelButton")
        self.deleteButton = QtWidgets.QPushButton(DeleteStudentDialog)
        self.deleteButton.setGeometry(QtCore.QRect(270, 140, 131, 35))
        self.deleteButton.setMinimumSize(QtCore.QSize(131, 35))
        self.deleteButton.setObjectName("deleteButton")

        self.retranslateUi(DeleteStudentDialog)
        QtCore.QMetaObject.connectSlotsByName(DeleteStudentDialog)

    def retranslateUi(self, DeleteStudentDialog):
        _translate = QtCore.QCoreApplication.translate
        DeleteStudentDialog.setWindowTitle(_translate("DeleteStudentDialog", "Delete Student?"))
        self.message.setText(_translate("DeleteStudentDialog", "Are you sure you want to delete this student?"))
        self.nameLabel.setText(_translate("DeleteStudentDialog", "blank"))
        self.cancelButton.setText(_translate("DeleteStudentDialog", "Cancel"))
        self.deleteButton.setText(_translate("DeleteStudentDialog", "Delete Student"))
