# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mediaCheckoutDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MediaDialog(object):
    def setupUi(self, MediaDialog):
        MediaDialog.setObjectName("MediaDialog")
        MediaDialog.resize(400, 175)
        self.buttonBox = QtWidgets.QDialogButtonBox(MediaDialog)
        self.buttonBox.setGeometry(QtCore.QRect(40, 130, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.studentIDInput = QtWidgets.QLineEdit(MediaDialog)
        self.studentIDInput.setGeometry(QtCore.QRect(50, 60, 311, 31))
        self.studentIDInput.setObjectName("studentIDInput")
        self.studentIDLabel = QtWidgets.QLabel(MediaDialog)
        self.studentIDLabel.setGeometry(QtCore.QRect(140, 20, 131, 17))
        self.studentIDLabel.setObjectName("studentIDLabel")
        self.validInputMessage = QtWidgets.QLabel(MediaDialog)
        self.validInputMessage.setGeometry(QtCore.QRect(50, 100, 311, 17))
        self.validInputMessage.setText("")
        self.validInputMessage.setObjectName("validInputMessage")

        self.retranslateUi(MediaDialog)
        self.buttonBox.accepted.connect(MediaDialog.accept)
        self.buttonBox.rejected.connect(MediaDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(MediaDialog)

    def retranslateUi(self, MediaDialog):
        _translate = QtCore.QCoreApplication.translate
        MediaDialog.setWindowTitle(_translate("MediaDialog", "Media Checkout"))
        self.studentIDLabel.setText(_translate("MediaDialog", "Enter Student ID:"))
