# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mediaPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MediaPage(object):
    def setupUi(self, MediaPage):
        MediaPage.setObjectName("MediaPage")
        MediaPage.setWindowModality(QtCore.Qt.ApplicationModal)
        MediaPage.resize(1283, 838)
        MediaPage.setModal(True)
        self.mediaTable = QtWidgets.QTableWidget(MediaPage)
        self.mediaTable.setGeometry(QtCore.QRect(30, 100, 1121, 701))
        self.mediaTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.mediaTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.mediaTable.setObjectName("mediaTable")
        self.mediaTable.setColumnCount(3)
        self.mediaTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.mediaTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.mediaTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.mediaTable.setHorizontalHeaderItem(2, item)
        self.mediaTable.horizontalHeader().setCascadingSectionResizes(False)
        self.mediaTable.horizontalHeader().setDefaultSectionSize(337)
        self.mediaTable.horizontalHeader().setMinimumSectionSize(120)
        self.mediaTable.horizontalHeader().setSortIndicatorShown(False)
        self.mediaTable.horizontalHeader().setStretchLastSection(True)
        self.closeButton = QtWidgets.QPushButton(MediaPage)
        self.closeButton.setGeometry(QtCore.QRect(1150, 20, 111, 51))
        self.closeButton.setObjectName("closeButton")
        self.title = QtWidgets.QLabel(MediaPage)
        self.title.setGeometry(QtCore.QRect(546, 26, 161, 41))
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.addButton = QtWidgets.QPushButton(MediaPage)
        self.addButton.setGeometry(QtCore.QRect(1160, 140, 99, 51))
        self.addButton.setObjectName("addButton")
        self.deleteButton = QtWidgets.QPushButton(MediaPage)
        self.deleteButton.setGeometry(QtCore.QRect(1160, 320, 99, 51))
        self.deleteButton.setObjectName("deleteButton")
        self.editButton = QtWidgets.QPushButton(MediaPage)
        self.editButton.setGeometry(QtCore.QRect(1160, 230, 99, 51))
        self.editButton.setObjectName("editButton")

        self.retranslateUi(MediaPage)
        QtCore.QMetaObject.connectSlotsByName(MediaPage)

    def retranslateUi(self, MediaPage):
        _translate = QtCore.QCoreApplication.translate
        MediaPage.setWindowTitle(_translate("MediaPage", "Media"))
        item = self.mediaTable.horizontalHeaderItem(0)
        item.setText(_translate("MediaPage", "Media ID"))
        item = self.mediaTable.horizontalHeaderItem(1)
        item.setText(_translate("MediaPage", "Media Title"))
        item = self.mediaTable.horizontalHeaderItem(2)
        item.setText(_translate("MediaPage", "Media Type"))
        self.closeButton.setText(_translate("MediaPage", "Close"))
        self.title.setText(_translate("MediaPage", "Media List"))
        self.addButton.setText(_translate("MediaPage", "Add"))
        self.deleteButton.setText(_translate("MediaPage", "Delete"))
        self.editButton.setText(_translate("MediaPage", "Edit"))
