# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mediaListPopup.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MediaListPopup(object):
    def setupUi(self, MediaListPopup):
        MediaListPopup.setObjectName("MediaListPopup")
        MediaListPopup.resize(1171, 607)
        MediaListPopup.setModal(True)
        self.mediaTable = QtWidgets.QTableWidget(MediaListPopup)
        self.mediaTable.setGeometry(QtCore.QRect(40, 90, 1091, 491))
        self.mediaTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.mediaTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.mediaTable.setObjectName("mediaTable")
        self.mediaTable.setColumnCount(3)
        self.mediaTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.mediaTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.mediaTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.mediaTable.setHorizontalHeaderItem(2, item)
        self.mediaTable.horizontalHeader().setCascadingSectionResizes(False)
        self.mediaTable.horizontalHeader().setDefaultSectionSize(360)
        self.mediaTable.horizontalHeader().setMinimumSectionSize(120)
        self.closeButton = QtWidgets.QPushButton(MediaListPopup)
        self.closeButton.setGeometry(QtCore.QRect(1030, 20, 99, 51))
        self.closeButton.setObjectName("closeButton")

        self.retranslateUi(MediaListPopup)
        QtCore.QMetaObject.connectSlotsByName(MediaListPopup)

    def retranslateUi(self, MediaListPopup):
        _translate = QtCore.QCoreApplication.translate
        MediaListPopup.setWindowTitle(_translate("MediaListPopup", "All Media"))
        item = self.mediaTable.horizontalHeaderItem(0)
        item.setText(_translate("MediaListPopup", "Media ID"))
        item = self.mediaTable.horizontalHeaderItem(1)
        item.setText(_translate("MediaListPopup", "Media Title"))
        item = self.mediaTable.horizontalHeaderItem(2)
        item.setText(_translate("MediaListPopup", "Media Type"))
        self.closeButton.setText(_translate("MediaListPopup", "Close"))
