# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'messagePopup.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MessagePopup(object):
    def setupUi(self, MessagePopup):
        MessagePopup.setObjectName("MessagePopup")
        MessagePopup.resize(387, 135)
        self.successLabel = QtWidgets.QLabel(MessagePopup)
        self.successLabel.setGeometry(QtCore.QRect(20, 20, 351, 61))
        self.successLabel.setWordWrap(True)
        self.successLabel.setObjectName("successLabel")
        self.studentNameLabel = QtWidgets.QLabel(MessagePopup)
        self.studentNameLabel.setGeometry(QtCore.QRect(100, 100, 351, 20))
        self.studentNameLabel.setObjectName("studentNameLabel")
        self.studentLabel = QtWidgets.QLabel(MessagePopup)
        self.studentLabel.setGeometry(QtCore.QRect(20, 100, 67, 17))
        self.studentLabel.setObjectName("studentLabel")
        self.okButton = QtWidgets.QPushButton(MessagePopup)
        self.okButton.setGeometry(QtCore.QRect(328, 100, 51, 27))
        self.okButton.setObjectName("okButton")

        self.retranslateUi(MessagePopup)
        QtCore.QMetaObject.connectSlotsByName(MessagePopup)

    def retranslateUi(self, MessagePopup):
        _translate = QtCore.QCoreApplication.translate
        MessagePopup.setWindowTitle(_translate("MessagePopup", "Message"))
        self.successLabel.setText(_translate("MessagePopup", "Message"))
        self.studentNameLabel.setText(_translate("MessagePopup", "studentName"))
        self.studentLabel.setText(_translate("MessagePopup", "Student:"))
        self.okButton.setText(_translate("MessagePopup", "OK"))
