# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'servicesPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ServicesPage(object):
    def setupUi(self, ServicesPage):
        ServicesPage.setObjectName("ServicesPage")
        ServicesPage.resize(632, 561)
        self.servicesTable = QtWidgets.QTableWidget(ServicesPage)
        self.servicesTable.setGeometry(QtCore.QRect(100, 100, 431, 341))
        self.servicesTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.servicesTable.setObjectName("servicesTable")
        self.servicesTable.setColumnCount(1)
        self.servicesTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.servicesTable.setHorizontalHeaderItem(0, item)
        self.servicesTable.horizontalHeader().setStretchLastSection(True)
        self.servicesTable.verticalHeader().setDefaultSectionSize(35)
        self.closeButton = QtWidgets.QPushButton(ServicesPage)
        self.closeButton.setGeometry(QtCore.QRect(510, 20, 99, 51))
        self.closeButton.setObjectName("closeButton")
        self.title = QtWidgets.QLabel(ServicesPage)
        self.title.setGeometry(QtCore.QRect(250, 20, 121, 51))
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.horizontalLayoutWidget = QtWidgets.QWidget(ServicesPage)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(100, 460, 431, 53))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.addButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.addButton.setMinimumSize(QtCore.QSize(99, 51))
        self.addButton.setObjectName("addButton")
        self.horizontalLayout.addWidget(self.addButton)
        self.editButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.editButton.setMinimumSize(QtCore.QSize(99, 51))
        self.editButton.setObjectName("editButton")
        self.horizontalLayout.addWidget(self.editButton)
        self.deleteButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.deleteButton.setMinimumSize(QtCore.QSize(99, 51))
        self.deleteButton.setObjectName("deleteButton")
        self.horizontalLayout.addWidget(self.deleteButton)

        self.retranslateUi(ServicesPage)
        QtCore.QMetaObject.connectSlotsByName(ServicesPage)

    def retranslateUi(self, ServicesPage):
        _translate = QtCore.QCoreApplication.translate
        ServicesPage.setWindowTitle(_translate("ServicesPage", "Services"))
        item = self.servicesTable.horizontalHeaderItem(0)
        item.setText(_translate("ServicesPage", "Service"))
        self.closeButton.setText(_translate("ServicesPage", "Close"))
        self.title.setText(_translate("ServicesPage", "Services"))
        self.addButton.setText(_translate("ServicesPage", "Add"))
        self.editButton.setText(_translate("ServicesPage", "Edit"))
        self.deleteButton.setText(_translate("ServicesPage", "Delete"))
