# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signInOrOutPopup.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(387, 113)
        self.successLabel = QtWidgets.QLabel(Form)
        self.successLabel.setGeometry(QtCore.QRect(20, 20, 201, 31))
        self.successLabel.setObjectName("successLabel")
        self.studentNameLabel = QtWidgets.QLabel(Form)
        self.studentNameLabel.setGeometry(QtCore.QRect(100, 80, 351, 20))
        self.studentNameLabel.setObjectName("studentNameLabel")
        self.studentLabel = QtWidgets.QLabel(Form)
        self.studentLabel.setGeometry(QtCore.QRect(20, 80, 67, 17))
        self.studentLabel.setObjectName("studentLabel")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.successLabel.setText(_translate("Form", "Message"))
        self.studentNameLabel.setText(_translate("Form", "studentName"))
        self.studentLabel.setText(_translate("Form", "Student:"))
