# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'visitHistoryPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VisitHistoryPage(object):
    def setupUi(self, VisitHistoryPage):
        VisitHistoryPage.setObjectName("VisitHistoryPage")
        VisitHistoryPage.resize(1556, 903)
        self.title = QtWidgets.QLabel(VisitHistoryPage)
        self.title.setGeometry(QtCore.QRect(646, 30, 141, 41))
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.closeButton = QtWidgets.QPushButton(VisitHistoryPage)
        self.closeButton.setGeometry(QtCore.QRect(1408, 20, 131, 51))
        self.closeButton.setObjectName("closeButton")
        self.visitsTable = QtWidgets.QTableWidget(VisitHistoryPage)
        self.visitsTable.setGeometry(QtCore.QRect(35, 100, 1381, 771))
        self.visitsTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.visitsTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.visitsTable.setAlternatingRowColors(True)
        self.visitsTable.setObjectName("visitsTable")
        self.visitsTable.setColumnCount(8)
        self.visitsTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.visitsTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.visitsTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.visitsTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.visitsTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.visitsTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.visitsTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.visitsTable.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.visitsTable.setHorizontalHeaderItem(7, item)
        self.visitsTable.horizontalHeader().setDefaultSectionSize(170)
        self.visitsTable.horizontalHeader().setStretchLastSection(True)
        self.visitsTable.verticalHeader().setDefaultSectionSize(35)
        self.visitsTable.verticalHeader().setMinimumSectionSize(30)
        self.editButton = QtWidgets.QPushButton(VisitHistoryPage)
        self.editButton.setGeometry(QtCore.QRect(1430, 110, 111, 51))
        self.editButton.setObjectName("editButton")
        self.importButton = QtWidgets.QPushButton(VisitHistoryPage)
        self.importButton.setGeometry(QtCore.QRect(1430, 200, 111, 51))
        self.importButton.setObjectName("importButton")

        self.retranslateUi(VisitHistoryPage)
        QtCore.QMetaObject.connectSlotsByName(VisitHistoryPage)

    def retranslateUi(self, VisitHistoryPage):
        _translate = QtCore.QCoreApplication.translate
        VisitHistoryPage.setWindowTitle(_translate("VisitHistoryPage", "Visit History"))
        self.title.setText(_translate("VisitHistoryPage", "Visit History"))
        self.closeButton.setText(_translate("VisitHistoryPage", "Close"))
        item = self.visitsTable.horizontalHeaderItem(0)
        item.setText(_translate("VisitHistoryPage", "Empl ID"))
        item = self.visitsTable.horizontalHeaderItem(1)
        item.setText(_translate("VisitHistoryPage", "Last Name"))
        item = self.visitsTable.horizontalHeaderItem(2)
        item.setText(_translate("VisitHistoryPage", "First Name"))
        item = self.visitsTable.horizontalHeaderItem(3)
        item.setText(_translate("VisitHistoryPage", "Course"))
        item = self.visitsTable.horizontalHeaderItem(4)
        item.setText(_translate("VisitHistoryPage", "Sign In Time"))
        item = self.visitsTable.horizontalHeaderItem(5)
        item.setText(_translate("VisitHistoryPage", "Sign Out Time"))
        item = self.visitsTable.horizontalHeaderItem(6)
        item.setText(_translate("VisitHistoryPage", "Service"))
        item = self.visitsTable.horizontalHeaderItem(7)
        item.setText(_translate("VisitHistoryPage", "Barcode"))
        self.editButton.setText(_translate("VisitHistoryPage", "Edit"))
        self.importButton.setText(_translate("VisitHistoryPage", "Import Visits"))
